<?php defined('BASEPATH') OR exit('No direct script access allowed');

$config['dealer/my_dealer/read'] = array(
	'd_id' => 'did',
	'd_des' => 'des',
	'd_shop' => 'shop',
	'a_id' => 'aid',
	'area' => 'area',
	'dc_id' => 'dcid',
	'dc_name' => 'category',
	'd_remark' => 'remark',
	'u_truename' => 'creator',
	'd_create_datetime' => 'create_datetime',
	'dl_name' => 'linker',
	'way' => 'way',
	'p_id' => 'pid',
	'p_name' => 'payterms',
	'd_debt1' => 'debt1',
	'd_debt2' => 'debt2',
	'd_delivered' => 'delivered',
	'd_received' => 'received',
	'd_balance' => 'balance',
    'd_virtual_produce' => 'virtual_produce',
    'd_virtual_delivered' => 'virtual_delivered',
    'd_virtual_balance' => 'virtual_balance',
    'd_virtual_received' => 'virtual_received',
);