<?php defined('BASEPATH') OR exit('No direct script access allowed');

$config['order/order_product_classify_model/select'] = array(
	'opc_id' => 'opcid',
	'opc_board' => 'board',
	'opc_area' => 'area',
	'opc_amount' => 'amount',
	'opc_optimize' => 'status',
	'opc_optimize_datetime' => 'optimize_datetime',
	'op_num' => 'order_product_num',
	'op_remark' => 'order_product_remark',
	'o_remark' => 'remark',
	'o_dealer' => 'dealer',
	'o_owner' => 'owner',
	'o_request_outdate' => 'request_outdate',
	'c_name' => 'classify',
);
$config['order/order_product_classify_model/select_optimize'] = array(
	'opc_id' => 'opcid',
	'opc_board' => 'board',
	'opc_area' => 'area',
	'opc_amount' => 'amount',
	'opc_optimize' => 'status',
	'opc_optimize_datetime' => 'optimize_datetime',
	'A.u_truename' => 'optimizer',
	'op_num' => 'order_product_num',
	'op_remark' => 'order_product_remark',
	'op_product' => 'product',
	'o_remark' => 'remark',
	'o_dealer' => 'dealer',
	'o_owner' => 'owner',
	'o_request_outdate' => 'request_outdate',
	'o_asure_datetime' => 'asure_datetime',
	'B.u_truename' => 'dismantler',
	'c_name' => 'classify',
);
$config['order/order_product_classify_model/select_current_workflow'] = array(
	'w_id' => 'wid',
	'w_no' => 'no',
	'w_type' => 'type',
	'w_name' => 'name',
	'w_name_en' => 'name_en',
	'w_file' => 'file',
);
$config['order/order_product_classify_model/select_electric_saw'] = array(
	'opc_id' => 'opcid',
	'opc_board' => 'board',
	'opc_area' => 'area',
	'opc_amount' => 'amount',
	'opc_optimize' => 'status',
	'opc_optimize_datetime' => 'optimize_datetime',
	'op_num' => 'order_product_num',
	'op_remark' => 'order_product_remark',
	'o_remark' => 'remark',
	'o_dealer' => 'dealer',
	'o_owner' => 'owner',
	'o_request_outdate' => 'request_outdate',
	'c_name' => 'classify',
);