<?php defined('BASEPATH') OR exit('No direct script access allowed');

$config['permission/form_model/select'] = array(
	'A.f_id' => 'fid',
	'A.f_name' => 'name',
	'A.f_label' => 'label',
	'A.f_form_type' => 'form_type',
	'A.f_url' => 'url',
    'A.f_placeholder' => 'placeholder',
    'A.f_dv' => 'dv',
    'A.f_max' => 'max',
    'A.f_min' => 'min',
    'A.f_maxlength' => 'maxlength',
    'A.f_pattern' => 'pattern',
    'A.f_classes' => 'classes',
    'A.f_ide' => 'ide',
	'B.f_name' => 'func',
	'm_name' => 'menu',
);
$config['permission/form_model/select_allowed'] = array(
	'A.f_id' => 'fid',
	'A.f_name' => 'name',
	'A.f_label' => 'label',
	'A.f_form_type' => 'form_type_V',
	'ft_name' => 'form_type_name',
	'A.f_url' => 'url',
    'A.f_placeholder' => 'placeholder',
    'A.f_dv' => 'dv',
    'A.f_readonly' => 'readonly_v',
    'READONLY.bt_name' => 'readonly_name',
    'A.f_required' => 'required_v',
    'REQUIRED.bt_name' => 'required_name',
    'A.f_multiple' => 'multiple_v',
    'MULTIPLE.bt_name' => 'multiple_name',
    'A.f_max' => 'max',
    'A.f_min' => 'min',
    'A.f_maxlength' => 'maxlength',
    'A.f_pattern' => 'pattern',
    'A.f_classes' => 'classes',
    'A.f_ide' => 'ide',
	'B.f_name' => 'func',
);
$config['permission/form_model/select_by_fid'] = array(
	'f_id' => 'fid',
	'f_name' => 'name',
	'f_label' => 'label',
	'f_form_type' => 'form_type',
	'f_url' => 'url',
	'f_func_id' => 'func_id',
    'f_placeholder' => 'placeholder',
    'f_dv' => 'dv',
    'f_max' => 'max',
    'f_min' => 'min',
    'f_maxlength' => 'maxlength',
    'f_pattern' => 'pattern',
    'f_classes' => 'classes',
    'f_ide' => 'ide'
);
