<?php defined('BASEPATH') OR exit('No direct script access allowed');

$config['produce/produce_abnormity/read'] = array(
	'opb_id' => 'opbid',
	'opb_board' => 'board',
	'o_num' => 'num',
	'o_remark' => 'remark',
	'status' => 'status',
	'o_dealer_name' => 'dealer',
	'o_dealer_linker' => 'dealer_linker',
	'o_dealer_address' => 'dealer_address',
	'o_dealer_phone' => 'dealer_phone',
	'o_owner' => 'owner',
	'o_request_outdate' => 'request_outdate',
	'u_truename' => 'creator',
	'create_datetime' => 'create_datetime',
);
$config['produce/produce_fitting/read'] = array(
	'op_id' => 'opid',
	'o_num' => 'num',
	'o_remark' => 'remark',
	'status' => 'status',
	'o_dealer_name' => 'dealer',
	'o_dealer_linker' => 'dealer_linker',
	'o_dealer_address' => 'dealer_address',
	'o_dealer_phone' => 'dealer_phone',
	'o_owner' => 'owner',
	'o_request_outdate' => 'request_outdate',
	'clear_datetime' => 'clear_datetime',
	'u_truename' => 'clearer',
);
$config['produce/produce_other/read'] = array(
	'op_id' => 'opid',
	'o_num' => 'num',
	'o_remark' => 'remark',
	'status' => 'status',
	'o_dealer_name' => 'dealer',
	'o_dealer_linker' => 'dealer_linker',
	'o_dealer_address' => 'dealer_address',
	'o_dealer_phone' => 'dealer_phone',
	'o_owner' => 'owner',
	'o_request_outdate' => 'request_outdate',
	'book_datetime' => 'book_datetime',
	'u_truename' => '"booker"',
);
$config['produce/produce_door/read'] = array(
	'opd_id' => 'opdid',
	'opd_board' => 'board',
	'opd_edge' => 'edge',
	'o_num' => 'num',
	'o_remark' => 'remark',
	'status' => 'status',
	'o_dealer_name' => 'dealer',
	'o_dealer_linker' => 'dealer_linker',
	'o_dealer_address' => 'dealer_address',
	'o_dealer_phone' => 'dealer_phone',
	'o_owner' => 'owner',
	'o_request_outdate' => 'request_outdate',
	'u_truename' => 'creator',
	'create_datetime' => 'create_datetime',
);