<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$config['dealer/dealer_model'] = array(
                                'company_type' => 'd_company_type',
                                'name' => 'd_name',
                                'num'=> 'd_num',
                                'area_id' => 'd_area_id',
                                'address' => 'd_address',
                                'discount' => 'd_discount',
                                'credit' => 'd_credit',
                                'payterms' => 'd_payterms',
                                'remark' => 'd_remark',
                                'creator' => 'd_creator',
                                'create_datetime' => 'd_create_datetime',
                                'debt1' => 'd_debt1',
                                'debt2' => 'd_debt2',
                                'debt3' => 'd_debt3',
                                'delivered' => 'd_delivered',
                                'received' => 'd_received',
                                'balance' => 'd_balance',
                                'status' => 'd_status',
                                'start_date' => 'd_start_date',
                        'start' => 'd_start'
                    );
$config['dealer/dealer_model/insert'] = array(
                                'company_type' => 'd_company_type',
                                'name' => 'd_name',
    'num'=> 'd_num',
                                'area_id' => 'd_area_id',
                                'address' => 'd_address',
                                'discount' => 'd_discount',
                                'credit' => 'd_credit',
                                'payterms' => 'd_payterms',
                                'down_payment' => 'd_down_payment',
                                'remark' => 'd_remark',
                                'creator' => 'd_creator',
                                'create_datetime' => 'd_create_datetime'
                    );
$config['dealer/dealer_model/insert_batch'] = array(
                                'company_type' => 'd_company_type',
                                'name' => 'd_name',
                                'area_id' => 'd_area_id',
                                'address' => 'd_address',
                                'discount' => 'd_discount',
                                'credit' => 'd_credit',
                                'payterms' => 'd_payterms',
    'down_payment' => 'd_down_payment',
                                'remark' => 'd_remark',
                                'creator' => 'd_creator',
                                'create_datetime' => 'd_create_datetime'
                    );
$config['dealer/dealer_model/update'] = array(
                                'company_type' => 'd_company_type',
                                'name' => 'd_name',
    'num'=> 'd_num',
                                'area_id' => 'd_area_id',
                                'address' => 'd_address',
                                'discount' => 'd_discount',
                                'credit' => 'd_credit',
                                'payterms' => 'd_payterms',
    'down_payment' => 'd_down_payment',
                                'remark' => 'd_remark',
                                'debt1' => 'd_debt1',
                                'debt2' => 'd_debt2',
                                'debt3' => 'd_debt3',
                                'delivered' => 'd_delivered',
                                'received' => 'd_received',
                                'balance' => 'd_balance',
                                'status' => 'd_status',
                                'start_date' => 'd_start_date',
                        'start' => 'd_start'
                    );
$config['dealer/dealer_model/update_batch'] = array(
                                'company_type' => 'd_company_type',
                                'name' => 'd_name',
    'num'=> 'd_num',
                                'area_id' => 'd_area_id',
                                'address' => 'd_address',
                                'discount' => 'd_discount',
                                'credit' => 'd_credit',
                                'payterms' => 'd_payterms',
    'down_payment' => 'd_down_payment',
                                'remark' => 'd_remark',
                                'debt1' => 'd_debt1',
                                'debt2' => 'd_debt2',
                                'debt3' => 'd_debt3',
                                'delivered' => 'd_delivered',
                                'received' => 'd_received',
                                'balance' => 'd_balance',
                                'status' => 'd_status',
                                'start_date' => 'd_start_date',
                        'start' => 'd_start'
                    );
