<?php defined('BASEPATH') OR exit('No direct script access allowed');

$config['order/order_model/insert_order'] = array(
	'dealer_id' => 'o_dealer_id',
	'dealer' => 'o_dealer',
	'checker' => 'o_checker',
	'checker_phone' => 'o_checker_phone',
	'payterms' => 'o_payterms',
	'payer' => 'o_payer',
	'payer_phone' => 'o_payer_phone',
	'logistics' => 'o_logistics',
	'out_method' => 'o_out_method',
	'delivery_area' => 'o_delivery_area',
	'delivery_address' => 'o_delivery_address',
	'delivery_linker' => 'o_delivery_linker',
	'delivery_phone' => 'o_delivery_phone',
	'owner' => 'o_owner',
	'remark' => 'o_remark',
	'dealer_remark' => 'o_dealer_remark',
	'request_outdate' => 'o_request_outdate',
	'creator' => 'o_creator',
	'create_datetime' => 'o_create_datetime',
	'flag' => 'o_flag',
);
$config['order/order_model/update_order'] = array(
	'owner' => 'o_owner',
	'checker' => 'o_checker',
	'checker_phone' => 'o_checker_phone',
	'payterms' => 'o_payterms',
	'payer' => 'o_payer',
	'payer_phone' => 'o_payer_phone',
	'logistics' => 'o_logistics',
	'out_method' => 'o_out_method',
	'delivery_area' => 'o_delivery_area',
	'delivery_address' => 'o_delivery_address',
	'delivery_linker' => 'o_delivery_linker',
	'delivery_phone' => 'o_delivery_phone',
	'remark' => 'o_remark',
	'dealer_remark' => 'o_dealer_remark',
	'sum' => 'o_sum',
	'sum_detail' => 'o_sum_detail',
	'sum_diff' => 'o_sum_diff',
	'asure_datetime' => 'o_asure_datetime',
	'request_outdate' => 'o_request_outdate',
	'payed_datetime' => 'o_payed_datetime',
	'end_datetime' => 'o_end_datetime',
	'stock_outted_id' => 'o_stock_outted_id',
	'flag' => 'o_flag',
	'cargo_no' => 'o_cargo_no',
);
$config['order/order_model/update_workflow'] = array(
	'status' => 'o_status',
	'dismantled_datetime' => 'o_dismantled_datetime',
	'checked_datetime' => 'o_checked_datetime',
	'quoted_datetime' => 'o_quoted_datetime',
	'asure_datetime' => 'o_asure_datetime',
	'payed_datetime' => 'o_payed_datetime',
	'sum' => 'o_sum',
	'sum_detail' => 'o_sum_detail',
	'pack' => 'o_pack',
	'pack_detail' => 'o_pack_detail',
);
$config['order/order_model/update_batch'] = array(
	'oid' => 'o_id',
	'asure_datetime' => 'o_asure_datetime',
	'request_outdate' => 'o_request_outdate',
	'payed_datetime' => 'o_payed_datetime',
	'pack' => 'o_pack',
	'pack_detail' => 'o_pack_detail',
	'cargo_no' => 'o_cargo_no',
);
$config['order/order_model/update_status'] = array(
	'id' => 'o_id',
	'status' => 'o_status',
);